const hyq_data = {
    "Sheet1": [
        {
            "title": "聖誕甜點親親工作坊\r\n(朱古力聖誕老人Cupcake)",
            "abstract": "當天會一齊整下聖誕老人cupcake，一齊玩下遊戲，快D黎參加啦！！",
            "host": "香港青年協會",
            "date": "22/12(日)",
            "time": "10:00-12:30",
            "location": "主單位",
            "fee": "免費",
            "target_audience": "-",
            "quota": "10對親子",
            "enroll_method": "親臨本單位報名或到報名網址報名",
            "enroll_deadline": "-",
            "enroll_link": "https://docs.google.com/forms/d/e/1FAIpQLSeyd5AKRA44wwncqufAuWYBLqLqFebud3_Q9Br5x3iVFW0k6w/closedform",
            "contact": "電話：2325 2383",
            "labels": "親子活動\r\n免费",
            "link": "http://psn.hkfyg.hk/play/detail/2107/"
        },
        {
            "title": "親子動起來露營\r\n(聖誕篇)",
            "abstract": "誠邀小朋友與家長動起來一齊去露營，透過活動讓孩子學習獨立﹑自理，亦讓親子一同參與活動，製造愉快回憶!",
            "host": "香港青年協會",
            "date": "28/12(六) - 29/12(日)",
            "time": "12:00－翌日14:00",
            "location": "賽馬會紅磡青年空間",
            "fee": "*150(會員)\r\n*180(非會員)\r\n*基金資肋6-29歲參加者費用$100。",
            "target_audience": "8 -60 歲家庭",
            "quota": "-",
            "enroll_method": "親臨本單位報名或到報名網址報名",
            "enroll_deadline": "27/12/2019 22:00",
            "enroll_notice": "*參加者請自備睡袋。",
            "enroll_link": "https://easymember.hk/eportal/Program/ProgramDetail.aspx?PID=19008889-11",
            "contact": "電話：2774 5300",
            "labels": "親子活動，戶外活動\r\n",
            "link": "http://psn.hkfyg.hk/play/detail/1894/"
        },
        {
            "title": "小腳板遊蹤之長洲遊",
            "abstract": "長洲觀音灣孕育出香港首個滑浪風帆奧運冠軍，長洲更有很多特色小食，活動將帶領小朋友欣賞這小島的傳奇色彩。",
            "host": "香港青年協會",
            "date": "28/12(六)",
            "time": "09:00-16:00",
            "location": "新界天水圍天耀邨天耀社區中心2-4樓，賽馬會天耀青年空間",
            "fee": "*80(會員)\r\n*110(非會員)\r\n*包車船費\r\n*自備午膳費",
            "target_audience": "6 至 12 歲",
            "quota": "-",
            "enroll_method": "親臨本單位報名或到報名網址報名",
            "enroll_deadline": "28/12/2019 22:00",
            "enroll_notice": "-",
            "enroll_link": "https://easymember.hk/eportal/Program/ProgramDetail.aspx?PID=19008359-1",
            "contact": "電話：2445 4868\r\nWhatsApp：+852 6811 2959",
            "labels": "兒童活動，戶外活動",
            "link": "http://psn.hkfyg.hk/play/detail/1954/"
        },
        {
            "title": "冬日送曖送入家 \r\n- 桌上遊戲家庭同樂日",
            "abstract": "星期日family day做咩好?又係海洋公園、迪士尼?\r\n12月22日12:00-14:00\r\n一齊落黎共渡一個暖意窩心嘅下晏！\r\n------------------\r\n參加者更可能免費帶走一副桌上遊戲~~~",
            "host": "香港青年協會",
            "date": "22/12",
            "time": "12:00-14:00",
            "location": "新界將軍澳明德邨明覺樓地下, 賽馬會將軍澳青年空間",
            "fee": "免費",
            "target_audience": "親子家庭（2人以上報名）",
            "quota": "-",
            "enroll_method": "填寫報名網址",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "https://forms.gle/zgRMHQB83nkfLkb6A",
            "contact": "電話：2623 3121",
            "labels": "家庭活動，親子活動，室內活動，免費",
            "link": "http://psn.hkfyg.hk/play/detail/2105/"
        },
        {
            "title": "「童」來放聖誕 - 攤位活動",
            "abstract": "~小食\r\n  DIY甜甜棉花糖\r\n  DIY脆脆爆米花\r\n  小鹿朱古力棉花糖\r\n~小手作\r\n  DIY小心意聖誕卡",
            "host": "香港青年協會",
            "date": "20-21/12/2019(周五&周六)",
            "time": "15:30-18:30",
            "location": "新界沙田大圍田心街1號隆亨邨隆亨社區中心3樓及5樓, 隆亨青年空間",
            "fee": "個別攤位收費",
            "target_audience": "-",
            "quota": "-",
            "enroll_method": "*致電26985565\r\n*WhatsApp：55426605",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "電話：2698 5565\r\nWhatsApp：55426605",
            "labels": "DIY活動，兒童活動",
            "link": "http://psn.hkfyg.hk/play/detail/2103/"
        },
        {
            "title": "聖誕擴香石工作坊",
            "abstract": "精美又天然既空氣清新劑！",
            "host": "香港青年協會",
            "date": "21/12/2019(週六)",
            "time": "14:30-16:00",
            "location": "新界沙田大圍田心街1號隆亨邨隆亨社區中心3樓及5樓, 隆亨青年空間",
            "fee": "40",
            "target_audience": "-",
            "quota": "-",
            "enroll_method": "*致電26985565\r\n*WhatsApp：55426606",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "電話：2698 5565\r\nWhatsApp：55426606",
            "labels": "青年活動，DIY活動",
            "link": "http://psn.hkfyg.hk/play/detail/2099/"
        },
        {
            "title": "聖誕廚房（朱古力批-少年）",
            "abstract": "聖誕廚房系列\r\n小朋友自己黎整又得\r\n同埋爸爸媽媽黎一齊整又得\r\n學習製作朱古力批，適合作聖誕派對小食！",
            "host": "香港青年協會",
            "date": "23/12/2019(週一)",
            "time": "15:00-17:00",
            "location": "橫頭磡邨宏光樓地下，黃大仙區，賽馬會橫頭磡青年空間",
            "fee": "120",
            "target_audience": "8-12歲小朋友",
            "quota": "-",
            "enroll_deadline": "21/12/2019 23:59",
            "enroll_notice": "-",
            "contact": "致電2337 7189向負責職員 Hkfyg Wth Easter 查詢",
            "labels": "兒童活動，美食，DIY活動",
            "link": "https://easymember.hk/eportal/Program/ProgramDetail.aspx?PID=18015230-9"
        },
        {
            "title": "聖誕廚房（樹頭蛋糕-親子)",
            "abstract": "聖誕廚房系列\r\n小朋友自己黎整又得\r\n同埋爸爸媽媽黎一齊整又得",
            "host": "香港青年協會",
            "date": "23/12/2019(週一)",
            "time": "19:00-21:00",
            "location": "橫頭磡邨宏光樓地下，黃大仙區，賽馬會橫頭磡青年空間",
            "fee": "200（2位1對）",
            "target_audience": "8-12歲小朋友",
            "quota": "-",
            "enroll_method": "填寫報名網址",
            "enroll_deadline": "21/12/2019 23:59",
            "enroll_link": "https://easymember.hk/eportal/Program/ProgramDetail.aspx?PID=18015230-9",
            "contact": "致電2337 7189向負責職員 Hkfyg Wth Easter 查詢",
            "labels": "親子活動，美食，DIY活動",
            "link": "https://easymember.hk/eportal/Program/ProgramDetail.aspx?PID=18015230-8"
        },
        {
            "title": "2019康城聖誕村嘉年華",
            "abstract": "又到聖誕、又到聖誕！\r\n\r\n\r\n聖誕節快到了，2019年12月20日是一年一度的康城聖誕村嘉年華，屆時將會舉辦一連串的聖誕活動， 除了聖誕樹亮燈儀式外，還有精彩的表演和豐富的攤位遊戲，更有聖誕老人迎接大家！\r\n\r\n歡迎大家穿著聖誕裝扮，一起感受聖誕的喜悅！",
            "host": "香港青年協會",
            "date": "20/12/2019(週五)",
            "time": "18:00-20:30",
            "location": "將軍澳日出康城首都 ，康城青年空間",
            "fee": "30/位\r\n*陪同家長免費（只限1位）",
            "target_audience": "3歲或以上會員及家長",
            "quota": "-",
            "enroll_method": "親臨康城青年空間",
            "enroll_deadline": "-",
            "enroll_link": "-",
            "contact": "電話：2702 2202",
            "labels": "會員，親子活動，3歲或以上兒童",
            "link": "http://psn.hkfyg.hk/play/detail/2081/"
        },
        {
            "title": "親子燒烤一叮",
            "abstract": "一家大小放假出外走走，電車遊覽，細心欣賞香港景色，再一起燒烤共慶新年。\r\n",
            "host": "香港青年協會",
            "date": "04/01/2020(週六)",
            "time": "13:00-21:00",
            "location": "九龍紅磡馬頭圍道48號家維村家興樓地下至五樓，賽馬會紅磡青年空間\r\n*集合時間地點: 13:00本單位地下大堂。\r\n*解散時間地點:21:00本單位地下大堂。",
            "fee": "*160（會員）\r\n*190（非會員）\r\n*基金資肋6-29歲參加者費用$100\r\n*活動費用已包括入場費交通費及燒烤費用。",
            "target_audience": "6 至 60 歲家庭",
            "quota": "-",
            "enroll_method": "填寫報名網址",
            "enroll_deadline": "03/01/2020 22:00",
            "enroll_notice": "*請穿著輕便運動服及波鞋、自備飲用水、防曬及防蚊用品。",
            "enroll_link": "https://easymember.hk/eportal/Program/ProgramDetail.aspx?PID=19008889-12",
            "contact": "電話：2774 5300",
            "labels": "戶外活動，親子活動，家庭活動",
            "link": "http://psn.hkfyg.hk/play/detail/1882/"
        },
        {
            "title": "小導遊初體驗@小導遊-遊大澳",
            "abstract": "透過活動學習策劃，包括行程安排、預算、所需物品和資料搜集等，訓練參加者執行、時間管理、應變能力和團隊精神等，有助日後與家人規劃旅程。同時透過遊歷大澳，認識離島特色及景點，共同製作拼貼展板並於單位展示，與區內小朋友一同分享，且有助日後規劃旅程，帶家人旅遊。",
            "host": "香港青年協會",
            "date": " 05/12/2019 - 02/01/2020 逢星期四16:30-18:00 及 30/12(星期一)",
            "time": "09:00-19:00",
            "location": "九龍黃大仙橫頭磡邨宏光樓地下， 賽馬會橫頭磡青年空間",
            "fee": "*80（會員）\r\n*110（非會員）",
            "target_audience": "8 至 14 歲",
            "quota": "-",
            "enroll_method": "填寫報名網址",
            "enroll_deadline": "01/12/2019 00:00",
            "enroll_notice": "*必須出席小組才能參與30/12/2019(一)的大澳遊歷活動\r\n\r\n*30/12/2019(一)大澳活動前請事先增值$50至八達通，請自備當日膳食費及交通費。\r\n\r\n*由於需乘搭巴士，請確保參加者沒有暈車浪。\r\n\r\n*公眾假期26/12/2019(四)暫停",
            "enroll_link": "https://easymember.hk/eportal/Program/ProgramDetail.aspx?PID=19008928-1",
            "contact": "電話：2337 7189",
            "labels": "戶外活動，8-14歲，兒童活動",
            "link": "http://psn.hkfyg.hk/play/detail/1864/"
        },
        {
            "title": "家居用品漂(北區)",
            "abstract": "分享二手家居用品, 費用全免。歡迎北區家長參與。\r\n規則\r\n1. 只需即場登記基本資料, 即可參與\r\n2. 所有二手家居用品均須可用及新淨\r\n3. 如欲捐出物品, 須於當天時段交由本會職員檢查核實\r\n4. 所有捐出物品均須由本會職員查核後擺放\r\n5. 每人每天最多可以換取兩項二手家居用品\r\n6. 功課練習、二手衣物、食物、大型物品電器及藥用品不設交換\r\n7. 所有易物均屬免費, 不涉金錢",
            "host": "香港青年協會",
            "date": " 每月第二及第四個星期二(公眾假期除外)",
            "time": "上午11時至12 時半",
            "location": "北區社區中心3樓 ",
            "fee": "免費",
            "target_audience": "家长",
            "quota": "-",
            "enroll_method": "-",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "電話：2429230",
            "labels": "家長活動，二手物品處理",
            "link": "http://psn.hkfyg.hk/play/detail/1855/"
        },
        {
            "title": "我有小煮意(青年篇)",
            "abstract": "由專業導師教授，曾任4星級酒店餅房師傅\r\n*所有收益將全數捐款，2020賣旗日籌款活動",
            "host": "香港青年協會",
            "date": "27/12/2019(週五)",
            "time": "19:00-21:00",
            "location": "新界沙田大圍田心街1號隆亨邨隆亨社區中心3樓及5樓, 隆亨青年空間",
            "fee": "100",
            "target_audience": "15-24歲",
            "quota": "-",
            "enroll_method": "-",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "電話：2698 5565 （嘉欣姑娘）",
            "labels": "DIY活動，美食活動，兒童活動，15-24歲",
            "link": "http://psn.hkfyg.hk/play/detail/2095/"
        },
        {
            "title": "花式足球/5人足球體驗",
            "abstract": "聖誕特備活動－運動編\r\n無論你有冇學過，識唔識踢波都啱玩！！\r\n最緊要係，免費！！！\r\n可致電隆亨青年空間報名，好搶手，報名要快！！",
            "host": "香港青年協會",
            "date": "14/12/2019(週六)",
            "time": "15:00-17:00",
            "location": "新翠邨足球場",
            "fee": "免費",
            "target_audience": "6-11歲",
            "quota": "15",
            "enroll_method": "致電隆亨青年空間2698 5565(梁Sir)",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "電話2698 5565(梁Sir)",
            "labels": "兒童活動，運動。6-11歲",
            "link": "http://psn.hkfyg.hk/play/detail/2087/"
        },
        {
            "title": "“共建我家Let’s make” 親子木工活動",
            "abstract": "透過親子木工製作，讓家人學會以鼓勵的方式溝通和耐心的聆聽，增進家庭關係",
            "host": "明愛香港仔綜合家庭服務中心",
            "date": "21/12/2019(星期六)",
            "time": "下午3:30-6:30",
            "location": "蒲窩青少年中心(香港仔大道116號)",
            "fee": "40 (會員) \r\n60 (非會員)",
            "target_audience": "\r\n親子(孩子為6-18歲以內的家庭)",
            "quota": "15人",
            "enroll_method": "致电25551993",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "電話25551993",
            "labels": "親子活動，DIY活動",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3665#.XfXT80YzZPY"
        },
        {
            "title": "延續愛‧親子義工隊",
            "abstract": "家長以身教形式帶領子女一起體驗做義工服務，發揮關愛共融精神，同時促進親子關係。",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "15/2、22/2、29/2/2020 (星期六)          ",
            "time": "上午10:00-11:30\r\n下午1:30-4:30",
            "location": "明愛天水圍綜合家庭服務中心",
            "fee": "免費",
            "target_audience": "親子或家庭(有3-6歲兒童優先)",
            "quota": "8對",
            "enroll_method": "親臨明愛天水圍綜閤家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "蔡韻沂姑娘、蔡文彬先生(註冊社工)",
            "labels": "親子活動，免費",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3663#.XfXVaUYzZPY"
        },
        {
            "title": "義工新春團拜2020",
            "abstract": "凝聚義工們一起歡聚佳節，分享應節食品，常存感恩的心，互相祝福。",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "\r\n7/2/2020(星期五)",
            "time": "\r\n晚上7:00-9:00",
            "location": "明腹天水圍綜合家庭服務中心",
            "fee": "本中心義工免費/義工家人每位$10 (大小同價)",
            "target_audience": "本中心義工及其家人",
            "quota": "40人",
            "enroll_method": "親臨明愛天水圍綜閤家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "儀姑娘、蔡文彬先生(註冊社工)",
            "labels": "義工活動",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3664#.XfXddUYzZPY"
        },
        {
            "title": "狼の俱樂部 男人好幫手",
            "abstract": "活動將會安排一連串義務工作體驗，讓男士好「幫」手的種子散播在社區不同的角落，做福他人之餘，也做福自己！",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "10/1、17/1、21/2及20/3/2020 (星期五)   ",
            "time": "晚上7:30-9:30",
            "location": "明愛天水圍綜合家庭服務中心",
            "fee": "免費",
            "target_audience": "有興趣男士(參加者需出席一次組前面談，以確認是否適合參加小組)",
            "quota": "15人",
            "enroll_method": "親臨明愛天水圍綜閤家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "黃志勇先生(註冊社工)",
            "labels": "義工活動，免費",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3662#.XfXX0kYzZPY"
        },
        {
            "title": "「心義同行」個人義工小組",
            "abstract": "透過定期的義工活動,讓義工培養及學習常存感恩「心」、開創新意「義」、能和而不「同」及齊坐言起「行」,從而達致助人自助的目標。",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "8/1、5/2、4/3及1/4/2020(星期三，每月一次，共四節)",
            "time": "上午10:00 - 12:00",
            "location": "\r\n明愛天水圍綜合家庭服務中心",
            "fee": "免費",
            "target_audience": "本中心義工(歡迎有興趣體驗/參與義工服務的人士)",
            "quota": "12人",
            "enroll_method": "親臨明愛天水圍綜閤家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "葉詠珊姑娘、蔡文彬先生(註冊社工)",
            "labels": "義工活動，免費",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3661#.XfXX00YzZPY"
        },
        {
            "title": "賀年鮮花插作",
            "abstract": "由中心義工擔任導師，分享賀年鮮花插作技巧及心得，讓義工們可以為家居增添節日氣氛之餘，又可以有彼此交流的機會。",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "7/1/2020(星期二)",
            "time": "上午10:00-11:30",
            "location": "明愛天水圍綜合家庭服務中心",
            "fee": "15/位",
            "target_audience": "中心義工及有興趣人士",
            "quota": "10人",
            "enroll_method": "親臨明愛天水圍綜閤家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "儀姑娘 (註冊社工)",
            "labels": "義工活動，DIY活動",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3660#.XfXX1EYzZPY"
        },
        {
            "title": "「 揉」情「蜜蜜」傳2020",
            "abstract": "1.體驗夫婦親密感與身體接觸的互動\r\n2.夫婦身體按摩與婚姻的「情」趣\r\n*參加者可獲送按摩油一支",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "\r\n21/2、28/2、6/3及13/3/2020(逄星期五晚上)",
            "time": "晚上7:30-9:30",
            "location": "明愛天水圍綜合家庭服務中心",
            "fee": "40 (會員) \r\n80 (非會員)",
            "target_audience": "夫婦",
            "quota": "8 對(夫婦必須同時出席)",
            "enroll_method": "親臨明愛天水圍綜閤家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "吳慧茹姑娘 (註冊社工、認可性治療師)",
            "labels": "夫婦活動",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3659#.XfXX1UYzZPY"
        },
        {
            "title": "浪漫温馨情人夜",
            "abstract": "甜蜜遊戲  2. 甜心抱抱  3. 情深感動在一刻  4. 浪漫燭光晚餐\r\n\r\n1.只供首次參加活動的夫婦參與\r\n\r\n2.提供3歲以上子女托兒服務，名額有限\r\n\r\n3.須自備子女晚餐",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "\r\n9/2/2020 (星期日)",
            "time": "下午5:30-晚上9:00",
            "location": "\r\n明愛天水圍綜合家庭服務中心",
            "fee": "100 (會員) \r\n200 (非會員)",
            "target_audience": "夫婦",
            "quota": "8 對(夫婦必須同時出席)",
            "enroll_method": "親臨明愛天水圍綜閤家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "陳慧玲姑娘、梁麥鳳婦女士(註冊社工)",
            "labels": "夫婦活動",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3657#.XfXX1kYzZPY"
        },
        {
            "title": "夫婦共享保健坊",
            "abstract": "想提升身心健康指數嗎？想紓緩因緊張生活帶來的肌肉疲勞及精神壓力？\r\n\r\n1. 身心營養補給秘方\r\n\r\n2. 頭肩頸腳等穴位保健按摩法\r\n\r\n3. 即場痛症諮詢，針對性示範及實習",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "25/4/2020(星期六)",
            "time": "上午9:30-11:00",
            "location": "明愛天水圍綜合家庭服務中心",
            "fee": "每對夫婦$100 (兩人共同出席並完成活動後，可獲贈超市禮券$100)",
            "target_audience": "夫婦同樂會會員",
            "quota": "\r\n5對",
            "enroll_method": "親臨明愛天水圍綜閤家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "吳趙婉麗姑娘 (註冊社工)",
            "labels": "夫婦活動",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3656#.XfXX2EYzZPY"
        },
        {
            "title": "夫婦賀年美食節2020",
            "abstract": "讓夫婦烹調製作自己的「自家賀年名菜」，讓夫婦在活動中體驗夫婦同心協作的樂趣\r\n\r\n1.本活動設有三歲以上的小朋友暫托服務。\r\n\r\n2.中心為每對夫婦提供150元的製作食物材料費。",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "\r\n18/1/2020(星期六)  ",
            "time": "上午10:00-12:30",
            "location": "明愛天水圍綜合家庭服務中心",
            "fee": "\r\n每對夫婦$100 (兩人共同出席並完成活動後，可獲贈超市禮券$100)",
            "target_audience": "夫婦同樂會會員",
            "quota": "\r\n8對",
            "enroll_method": "親臨明愛天水圍綜閤家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "\r\n吳慧茹姑娘(註冊社工)",
            "labels": "夫婦活動",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3655#.XfXX2UYzZPY"
        },
        {
            "title": "「憤怒向左走，向右走」 體驗工作坊",
            "abstract": "憤怒是一種情緒的自然表達，並無對錯之分。面對憤怒，你或許感到害怕，否定它的存在，竭力把它牢固的壓抑在心裡。另一方面，你可能被它控制，讓它隨時發洩出來，為自己和身邊的人帶來傷害。誠意邀請你在一個互相信任及安全的環境下，透過不同的媒介去接觸、了解、覺察埋藏在心裡的憤怒；學習用適合自己的途徑表達，找出它背後的訊息，尋找面對及轉化憤怒的方法。",
            "host": "明愛賽馬會心泉發展中心",
            "date": "下午班：\r\n\r\n日期: 2019年10月29日至11月19日(共4節, 星期二)\r\n\r\n時間:下午2:30-4:30\r\n\r\n週末班：\r\n\r\n日期: 2019年11月16日(星期六)\r\n\r\n時間:上午10:00-下午5:30",
            "time": "-",
            "location": "荃灣城門道 9 號  明愛賽馬會荃灣服務樓 8樓802室",
            "fee": "400/位",
            "target_audience": "想處理內心憤怒的朋友",
            "quota": "20人",
            "enroll_method": "親臨荃灣城門道 9 號9樓，或填寫報名網址",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "https://docs.google.com/forms/d/e/1FAIpQLSdgr7pL5UIjU78vqGW2Yn4RB2-EzwZKGg-dMFtO2PglrBDDLA/closedform",
            "contact": "電話3707 2000 ",
            "labels": "個人活動，情緒活動",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3613#.XfXa5UYzZPZ"
        },
        {
            "title": "幼兒故事天地 (第12期)",
            "abstract": "透過繪本故事伴讀，提升孩子的閱讀興趣，培養良好品德。                     \r\n\r\n1. 趣味繪本故事\r\n\r\n2. 創意小手工",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "7/3/2020(星期六)",
            "time": "上午10:00-11:00",
            "location": "明愛天水圍綜合家庭服務中心",
            "fee": "10 (會員) \r\n20 (非會員)",
            "target_audience": "4-6歲兒童",
            "quota": "15人",
            "enroll_method": "親臨明愛天水圍綜合家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "陳麗珠姑娘(註冊社工)",
            "labels": "兒童活動，4-6歲",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3647#.XfXbtUYzZPY"
        },
        {
            "title": "幼兒故事天地 (第11期)",
            "abstract": "閱讀習慣及良好品德的培養都非一朝一夕能做到，此恆常活動鼓勵孩子愛上「悅」讀及培育好品德。",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "\r\n11/1/2020(星期六)",
            "time": "上午10:00-11:00",
            "location": "明愛天水圍綜合家庭服務中心",
            "fee": "10(會員)\r\n20(非會員)",
            "target_audience": "4-6歲兒童",
            "quota": "15人",
            "enroll_method": "親臨明愛天水圍綜合家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "\r\n柯禕慧姑娘(註冊社工)",
            "labels": "兒童活動，4-6歲",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3646#.XfXbtkYzZPY"
        },
        {
            "title": "幼兒個人情緒成長系列(2)小巧創作活動",
            "abstract": "透過遊戲、分享及石膏公仔創作------培養孩子仁愛品格強項，建立情緒智慧",
            "host": "明愛天水圍綜合家庭服務中心",
            "date": "22/02/2020 (星期六)",
            "time": "上午10:00-12:00",
            "location": "明愛天水圍綜合家庭服務中心",
            "fee": "10(會員)\r\n20(非會員)",
            "target_audience": "7-12歲兒童",
            "quota": "10人",
            "enroll_method": "親臨明愛天水圍綜合家庭服務中心",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "李笑芬姑娘(註冊社工)",
            "labels": "兒童活動，7-12歲",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3645#.XfXbt0YzZPY"
        },
        {
            "title": "親子故事扎柒體驗",
            "abstract": "以《藍色小洋裝》繪本及天然扎柒為校園生活及家長照顧壓力減減壓。\r\n加入資訊科技元素，為活動加添新意",
            "host": "明愛香港仔綜合家庭服務中心",
            "date": "2019年12月21日",
            "time": "上午10:00至13:30",
            "location": "元創方PMQ(中環鴨巴甸街35號)",
            "fee": "每對親子$100按金(活動當日出席及完成活動後將全數退回)",
            "target_audience": "5-12歲小朋友及其家長(每對親子2份素材)",
            "quota": "12對親子",
            "enroll_method": "致電25551993梁先生",
            "enroll_deadline": "-",
            "enroll_notice": "-",
            "enroll_link": "-",
            "contact": "聯絡人25551993(梁先生)",
            "labels": "親子活動，免費",
            "link": "https://family.caritas.org.hk/zh-hk/activities/view/3616#.XfXbuEYzZPY"
        }
    ]
};